/*
 * BankATMLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.swaggerhub.virtserver;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://virtserver.swaggerhub.com/W7354/BankATM_V2/1.0.0";

}
